# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: users
  host: localhost
  user: sandip
  password: password
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: users
  host: localhost
  pool: 5
  user: sandip
  password: password


test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: users
  host: localhost
  pool: 5
  user: sandip
  password: password

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: users
  host: localhost
  pool: 5
  user: sandip
  password: password